FORMAT: 1A
HOST: http://ec2-52-77-147-66.ap-southeast-1.compute.amazonaws.com:8080/guestservice

# Guest Service

The purpose of this service is to manage Guest details like Personal Details, Identification details, Visa details, Social media account details, Loyalty Levels etc.
This document explains how to get started using the Guest api. This document is intended for developers who want to write applications that can interact with the Guest API.
The main features of the API are as follows-

 

- Delete guest Information.

- Retrieve guests information by guest id

- Update guest information

- Retrieve guests information list

- Insert Guest Information

- Retrieve guests information by user account id

## Version 1.0.0.1


## Authentication
*Guest API* uses OAuth Authorization. Once you have acquired your token you can use it to access protected resources within token' scope.

# Group Guests    
## Guests Collection [/guests{?lastNameContains,firstNameContains,guestIds,shipId,stateroomIds,reservationStartDate,reservationEndDate,modifiedParts,reservationIds,passports,name,depth,pageNumber,maxResult,orderBy}]

### List Guests [GET]
List guest data

+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json, text/plain
            
+ Parameters

    + lastNameContains (, optional)

        search based on last name
    
    + firstNameContains (, optional)

        search based on first name

    + guestIds (, optional)

        search based on guestids

    + shipId (, optional)

        search based on ship id

    + stateroomIds (, optional)

        search based on state room ids

    + reservationStartDate (, optional)

        search based on reservation Start Date

    + reservationEndDate (, optional)

        search based on reservation End Date

    + modifiedParts (, optional)

        search based on modified Parts

    + reservationIds (, optional)

        search based on reservation Ids

    + passports (, optional)

        search based on passport

    + name (, optional)

        search based on name
        
    + depth (, optional) 
    
        search based on depth
        
    + pageNumber (, optional) 
    
        search based on pageNumber
        
    + maxResult (, optional) 
    
        search based on maxResult
        
    + orderBy (, optional) 
    
        search based on orderBy
        
+ Response 200 (application/json)

        {
            OK
        }

    + Attributes (array[Guest])   
        
## Guests By Id [/guests/{id}]
+ Parameters
    + id: 101 (, required)

        guest id to extract guest record
            
### Retrieve Guest [GET]
Retrieves a guest based on guest id
        
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json   

+ Response 200 (application/json)

        {
            OK
        }
        
    +   Attributes (Guest)

### Update Guest [PUT]
Update guest.
    
+ Request

    + Attributes (Guest)
    
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json 
+ Response 200 (application/json)

        {
            OK
        }

    + Attributes (Guest)
    
### Delete Guest [DELETE]
Delete a guest
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json  
+ Response 200 (application/json)

        {
            OK
        }

## Guests Account By Id [/guests/account/{id}]

+ Parameters
    + id: 101 (, required)

        user account id to extract guest record


### GuestsAccountById [GET]
Retrieves guest by user account id
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json  
+ Response 200 (application/json)

        {
            OK
        }

    + Attributes (Guest)
        
## Insert Guest [/guests]

### Insert Guest [POST]
Insert guest data

+ Request 

    + Attributes (Guest)
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json  
+ Response 201 (application/json)

        {
            Created
        }

    + Attributes (Guest)
 
# Group Addresses

## Address List and Insert [/guestsAddress/{id}]

+ Parameters

    + id: 101 (string, required)

        guest id of guest required to retrieve and insert address collection
        
### List Addresses [GET]
List address data
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
+ Response 200 (application/json)

        {
            OK
        }

    + Attributes (array[address])
        
### Insert Guest [POST]
Insert guest

+ Request

    + Attributes (address)
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json    
+ Response 201 (application/json)

        {
            Created
        }

## Address Retrieval, Updation and Deletion [/guests/{id}/address/{addressId}]
+ Parameters
    + id: 101 (string, required)

        guest id of guest required to retrieve and insert address collection
        
    + addressId: 1234 (string, required)

        guest id of guest required to retrieve and insert address collection
        
### Retrieve Addresses [GET]
Retrieve address
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
+ Response 200 (application/json)

        {
            OK
        }
        
    +   Attributes (address)

### Update address [PUT]
Update address

+ Request

    + Attributes (address)
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
+ Response 200 (application/json)

        {
            OK
        }

### Delete Address [DELETE]
Delete address
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
+ Response 200 (application/json)

        {
            OK
        }
        
# Group GuestReservations

## List [/GuestReservations{?lastNameContains,firstNameContains,guestIds,shipId,stateroomIds,reservationStartDate,reservationEndDate,modifiedParts,reservationIds,passports,name,depth,pageNumber,maxResult,orderBy}]

### List Reservations [GET]
List reservation data
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
+ Parameters

    + lastNameContains (, optional)

        search based on last name
    
    + firstNameContains (, optional)

        search based on first name

    + guestIds (, optional)

        search based on guestids

    + shipId (, optional)

        search based on ship id

    + stateroomIds (, optional)

        search based on state room ids

    + reservationStartDate (, optional)

        search based on reservation Start Date

    + reservationEndDate (, optional)

        search based on reservation End Date

    + modifiedParts (, optional)

        search based on modified Parts

    + reservationIds (, optional)

        search based on reservation Ids

    + passports (, optional)

        search based on passport

    + name (, optional)

        search based on name
        
    + depth (, optional) 
    
        search based on depth
        
    + pageNumber (, optional) 
    
        search based on pageNumber
        
    + maxResult (, optional) 
    
        search based on maxResult
        
    + orderBy (, optional) 
    
        search based on orderBy
        
+ Response 200 (application/json)

        {
            OK
        }

    + Attributes (array[reservation])  
    
# Group Phones

## Phone List [/Guests/{guestId}/Phones{?parts}]

+ Parameters
    + guestId: 101 (string, required)
        guest id of guest required to list phone
        
### List Phone [GET]
Retrieves phone list

+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
        
+ Parameters
    + parts (, optional)
        This parameter defines the Parts of resource that will be returned in the result set.
        
+ Response 200 (application/json)

        {
            OK
        }
            
    + Attributes (array[phone])   

## Insert Phone [/Guests/{guestId}/Phones]

+ Parameters
    + guestId: 101 (string, required)
        guest id of guest required to list phone

### Insert Phone [POST]
Insert phone
+ Request

    + Attributes (phone)
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json    
+ Response 201 (application/json)

        {
            Created
        }

## Get Phone [/Guests/{guestId}/Phones/{phoneId}{?parts}]

+ Parameters
    + guestId: 101 (string, required)
        id of the guest whose phone detail needs to be retrieved.
    + phoneId: 5632 (string, required)
        Unique identifier assigned  to a guest’s phone.
        
### Retrieves Phone [GET /Guests/{guestId}/Phones/{phoneId}{?parts}]
Retrieves phone by phone id and guest id
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json
+ Parameters

    + parts (, optional)
    
        This parameter defines the Parts of resource that will be returned in the result set.
        
+ Response 200 (application/json)

        {
            OK
        }

    + Attributes (array[phone])   

## Update and Delete Phone [/Guests/{guestId}/Phones/{phoneId}]

+ Parameters
    + guestId: 101 (string, required)
        id of the guest whose phone detail needs to be retrieved.
    + phoneId: 5632 (string, required) 
        Unique identifier assigned  to a guest’s phone.
        
### Update Phone [PUT]
Update phone

+ Request

    + Attributes (phone)
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json    
+ Response 200 (application/json)

        {
            OK
        }
        
### Delete Phone [DELETE]
Delete phone
+ Request
    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzY29wZSI6WyJ3cml0ZSJdLCJleHAiOjE0NjczNjg3OTYsImF1dGhvcml0aWVzIjpbIlJPTEUiXSwianRpIjoiYmE5YmNhYWItMDBkOC00ZGQ3LTliYzMtNjkwNGY1N2QwYmQ2IiwiY2xpZW50X2lkIjoibm9ybWFsLWFwcCJ9.VYWVY4IZMWdHp6kb83cebnX9jv2auf8nuG3ZUW8ANoARZ39AlhPE7w3uVrs29-zW_xHLHBpSJjyZt9fH-LXHs5neUBq6Wn54vmeliCDYjmJMZaQDe9A7cXUIu42tsAh4IciYcxUolTZXWJz0KJzgXBurM8UarlJPTo_h_lSWsBqnG0BD6k5GzhogishVVnYY0lWL_8gDxjv9kLebl2pgAwL3Ze6AV8CRuvSe9Bn0kn-1Kh9d5DVrwhHH7Mx52MHeH_xw5esc9L6x6y3i_tkwaFw_6kwjFJ-6Y2SyGmnnrtbcIvnwHtSQDqyoAC8SbiYI-0rpLT-c2xcT0R_W2QGJWQ
            Content-Type: application/json    
+ Response 200 (application/json)

        {
            OK
        }
        
# Data Structures

## Guest (object)

### Properties
+ "id": 1234 (number, required)
+ "title": MSTR (string, optional) 
+ "firstName": ETHAN (string, optional) 
+ "middleName": MLAWSKI (string, optional) 
+ "lastName": MLAWSKI (string, optional) 
+ "nickName": xyz (string, optional) 
+ "preferredName": xyz (string, optional) 
+ "suffix": xyz (string, optional) 
+ "birthDate": '1972-10-03' (string, optional) 
+ "gender": M (string, optional) 
+ "maritalStatus": Unknown (string, optional) 
+ "occupation": xyz (string, optional) 
+ "email": 'kristie_buss@yahoo.com' (string, optional) 
+ "alternateEmail": 'kristie_buss@yahoo.com' (string, optional) 
+ "anniversaryDate": '1972-10-03' (string, optional) 
+ "birthCountryId" (number, optional) 
+ "citizenshipCountryId" (number, optional) 
+ "userAccountId" (number, optional) 
+ "addedDate": '12-3-1990' (string, required) 
+ "lastModifiedDate": '12-3-1990' (string, required) 
+ "deletedFlag": false (boolean, required)'
+ "phones" (array[phone], optional) 
+ "reservations" (array[reservation], optional) 
+ "addresses" (array[address], optional) 
+ "identifications" (array[identification], optional) 
+ "visas" (array[visa], optional) 
+ "loyaltyLevels" (array[loyaltyLevel], optional) 

## phone (object)

### Properties
+ "phoneId": 75021 (number, required) 
+ "phoneTypeId": 1 (string, optional) 
+ "countryId": 232 (number, optional) 
+ "areaCode": xyz (string, optional) 
+ "number": 2019703511 (string, optional) 
+ "lastModifiedDate": '2016-03-29' (string, required) 


## reservation (object)

### Properties
+ "guestReservationId": 30826 (number, required) 
+ "reservationNumber": 7Q5QP7 (string, optional) 
+ "reservationId": 7026 (number, optional) 
+ "stateroomId": 849 (number, optional) 
+ "embarkDate": '2016-03-21' (string, optional) 
+ "lastModifiedDate": 1459313689000 (string, optional) 
+ "vipflag": 1 (boolean, optional) 
+ "primaryFlag": 1 (boolean, optional) 
+ "debarkDate": '2016-04-03' (string, optional) 
+ "statusId": 1 (string, optional) 
+ "loyaltyLevelTypeId": 102 (number, optional) 
+ "identificationId": 84159 (number, optional) 
+ "idVerifiedFlag": 0 (boolean, optional) 
+ "sequenceNumber": 1 (number, optional) 
+ "folioNumber": 4197 (string, optional) 
+ "folios" (array[folio], optional) 


## folio (object)

### Properties
+ "folioId": 55921 (string, required) 
+ "folioNumber": 4197 (string, optional) 
+ "guestReservationId": 7 (number, optional) 
+ "accessCardNumber": 31522105 (string, optional) 
+ "folioStatus": A (string, optional) 
+ "isGangwayAllowed": 0 (boolean, optional) 


## address (object)


### Properties
+ "addressId": 48443 (number, required) 
+ "line1": APT 202 (string, optional) 
+ "line2":  100 MISTY PINES CIR (string, optional) 
+ "city": WEST PARK (string, optional) 
+ "state": FL (string, optional) 
+ "lastModifiedDate": 1458556148000 (string, required) 
+ "stateId": 103 (number, optional) 
+ "countryId": 232 (number, optional) 
+ "zip": 07081 (string, optional) 


## identification (object)


### Properties
+ "identificationId": 84259 (number, required) 
+ "documentTypeId": 1 (number, optional) 
+ "number": 221377293 (string, optional) 
+ "issueCountryId": 101 (number, optional) 
+ "expiryDate": '2017-02-14' (string, optional) 
+ "scanCopyMediaItemId": 5236 (number, optional) 
+ "guestImageMediaItemId": 1235 (number, optional) 
+ "lastModifiedDate": 1459240885000 (string, required) 
+ "guestId": 4275 (number, optional) 


## visa (object)


### Properties
+ "visaId": 1001 (number, required) 
+ "issueCountryId": 101 (number, optional) 
+ "number": AX102 (string, optional) 
+ "issueDate": '2016-03-29' (string, optional) 
+ "expiryDate": '2016-03-29' (string, optional) 
+ "numberOfEntries": 12 (string, optional) 
+ "mediaItemId": 102 (number, optional) 
+ "lastModifiedDate": '2016-03-29' (string, required) 


## loyaltyLevel (object)


### Properties
+ "loyaltyLevelId": 79692 (number, required) 
+ "loyaltyLevelTypeId": 101 (number, optional) 
+ "numberOfCruiseNights": 8 (number, optional) 
+ "vifpnumber": xyz (string, optional) 
+ "lastModifiedDate": '2016-03-29' (string, required)